entities:
  test:
    mob_type: HUSK
    name: '&c&lThe Scary'
    health: 10
    equipment:
      helmet: LEATHER_HELMET
      chestplate: DIAMOND_CHESTPLATE
      leggings: IRON_LEGGINGS
      boots: IRON_BOOTS
      main_hand: IRON_SWORD
      off_hand: SHIELD

  test1:
    weapon: iron_sword
    mob_type: SKELETON
    name: The Scary 2!!!
    health: 5
    movement_speed: 0.3
    equipment:
      helmet: CHAINMAIL_HELMET
      chestplate: LEATHER_CHESTPLATE
      leggings: GOLDEN_LEGGINGS
      boots: DIAMOND_BOOTS
      main_hand: bow
  testLeader:
    weapon: diamond_Sword
    mob_type: HUSK
    name: '&aThe Scary Leader'
    equipment:
      helmet: GOLDEN_HELMET
      chestplate: DIAMOND_CHESTPLATE
      leggings: IRON_LEGGINGS
      boots: LEATHER_BOOTS
      main_hand: bow


group:
  testGroup:
    members: # Put entites here. They wll probably be placed in order.
      test: 40
      test1: 10
    leader: testLeader # NOTE LEADERS ARE REQUIRED
    ai: true #use this to control whether the group starts with ai or not

