name: CustomSpawning
version: '1.0-SNAPSHOT'
main: org.milk4lyfe.customSpawning.mobplusplus
api-version: '1.21'
commands:
  spawn:
    description: spawns stuff
    permission: mobplusplus.spawn
  mobPlusPlusconfigReload:
    description: reloads da config
    permission: mobplusplus.reload